#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Blast\DevKit\Console\Application;

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

$application = new Application();
$application->run();
