blast-project:
    options:
       active: true

    repositories:
        CoreBundle:
            active: true

        DoctrinePgsqlBundle:
            active: true

        DoctrineSessionBundle:
            active: true

        OuterExtensionBundle:
            active: true

        BaseEntitiesBundle:
            active: true

        UtilsBundle:
            active: true
            
        TestsBundle:
            active: true

        bundle-skeleton:
            active: true

libre-informatique:
    options:
       active: true

    repositories:
        EcommerceBundle:
            active: true
            
        VarietiesBundle:
            active: true
            
        EmailBundle:
            active: true
            
        SeedBatchBundle:
            active: true
            
        CRMBundle:
            active: true
            
        SonataSyliusUserBundle:
            active: true
            
        EmailCRMBundle:
            active: true
            
        MediaBundle:
            active: true
            
        DecoratorBundle:
            active: true
