blast-project:
    options:
       active: true

    repositories:
        CoreBundle:
            active: true

        DoctrinePgsqlBundle:
            active: false

        DoctrineSessionBundle:
            active: false

        OuterExtensionBundle:
            active: false

        BaseEntitiesBundle:
            active: false

        UtilsBundle:
            active: false

        Blast:
            active: false
            is_project: true

libre-informatique:
    options:
       active: false

    repositories:
      